const wmo = {
    0:'Clear Sky',
    1:'Mainly Clear',
    2:'Partly Cloudy',
    3:'Overcast',
    45:'Fog',
    48:'Depositing Rime Fog',
    51:"Light Drizzle",
    53:"Moderate Drizzle",
    55:"Intense Drizzle",
    56:"Light Freezing Drizzle",
    57:"Intense Freezing Drizzle",
    61:"Light Rain",
    63:"Moderate Rain",
    65:"Heavy Rain",
    66:"Light Freezing Rain",
    67:"Heavy Freezing Rain",
    71:"Light Snow Fall",
    73:"Moderate Snow Fall",
    75:"Heavy Snow Fall", 
    77:"Snow Grains",
    80:"Light Rain Showers",
    81:"Moderate Rain Showers",
    82:"Heavy Rain Showers",
    85:"Light Snow Showers",
    86:"Heavy Snow Showers",
    95:"Slight Thunderstorm" ,
    951:"Moderate Thunderstorm", 
    96:"Thunderstorm With Light Hail",
    99:"Thunderstorm With Heavy Hail"
  }

  export default wmo;